# Generated by Django 3.2.9 on 2021-11-27 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New lobby', max_length=50)),
                ('password', models.CharField(default='12345', max_length=50)),
                ('update_id', models.IntegerField(default=0)),
                ('active_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_lobby', to='authsys.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new hero', max_length=50)),
                ('hp', models.IntegerField(default=25)),
                ('damage', models.IntegerField(default=7)),
                ('speed', models.IntegerField(default=3)),
                ('movement', models.IntegerField(default=3)),
                ('armor', models.IntegerField(default=0)),
                ('attack_range', models.IntegerField(default=1)),
                ('is_proto', models.BooleanField(default=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('img_src', models.ImageField(blank=True, null=True, upload_to='')),
                ('lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lobby')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authsys.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authsys.userprofile')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lobby')),
            ],
        ),
    ]
