# Generated by Django 3.2.9 on 2021-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_hero_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='max_hp',
            field=models.IntegerField(default=25),
        ),
    ]
