# Generated by Django 3.2.9 on 2021-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
