# Generated by Django 3.2.9 on 2021-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_hero_max_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='img_src',
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='heroes_images/'),
        ),
    ]
