# Generated by Django 3.2.9 on 2021-12-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20211218_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='game.lobby'),
        ),
    ]
