# Generated by Django 3.2.9 on 2021-12-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_chatmessage_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.AddField(
            model_name='hero',
            name='image_src',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
